### ISSUE TITLE
Django Error message when normalizer throws exception

### ISSUE THREAD

**Issue by Nurts** [pipermerriam/ethereum-function-signature-registry#60]
### What is wrong?

Server Error in https://www.4byte.directory/import-abi/, when normalizer function throws an exception.
![func_error](https://user-images.githubusercontent.com/38371660/89818096-0af47d00-db6b-11ea-9660-233aa8e56140.png)

### Why it happened?
When importing from Contract ABI, if json has error similar to following (type name error):
`[{
    "constant":false,
    "inputs":[
        {"name":"some_id", "type":"ufint"},
        {"name":"some_address", "type":"addrsess"},
        {"name":"some_string", "type":"straing"}
        ],
    "outputs":[],
    "name":"SomeFunction",
    "type":"function"
}]`

Function `import_from_contract_abi(cls, contract_abi)` returns array with `None`;
Which is not iterable with zip, resulting in uncaught exception

### How can it be fixed

- Check the returned array for None elements
- If there are, raise an exception (or handle it by removing None elements)

**Comment by pipermerriam** [comment]
I think that we should instead fix it so that the array doesn't end up with null elements in it.

I believe this is the offending line:

https://github.com/pipermerriam/ethereum-function-signature-registry/blob/7c0828222b76cec841560c3554ae9008d4bc1467/func_sig_registry/registry/models.py#L92

In the event that it hits the exception context there it will implicitely return `None` from the function.  We should simply emulate an empty response from `get_or_create` which according to a brief search of the django documentation should just be an empty tuple.

**Comment by Nurts** [comment]
Thanks for the advice, follow up question:
* Since, it won't be counted as imported, it will be counted as `num_duplicates`
https://github.com/pipermerriam/ethereum-function-signature-registry/blob/7c0828222b76cec841560c3554ae9008d4bc1467/func_sig_registry/registry/forms.py#L100
Is it okay if we report it as a duplicate ?

**Comment by pipermerriam** [comment]
I think it would be better to just include it as a new value `num_ignored` which can be calculated by counting how many empty tuples are returned.
